export type FaqQuestion = {
  question: string;
  answer: string;
};

export type FaqSection = {
  slug: string;
  title: string;
  intro: string;
  questions: FaqQuestion[];
};

export const faqSections: FaqSection[] = [
  {
    slug: "umzug-allgemein",
    title: "Umzug allgemein",
    intro: "Antworten zu privaten und gewerblichen Umzügen sowie zum grundsätzlichen Leistungsumfang von MTM.",
    questions: [
      { question: "Welche Umzüge übernimmt MTM?", answer: "MTM unterstützt private und gewerbliche Umzüge in Hannover & Umland. Der genaue Umfang wird vor der Durchführung persönlich abgestimmt." },
      { question: "Sind auch kleine Umzüge möglich?", answer: "Ja. Auch einzelne Zimmer, Teilumzüge oder kleinere Transporte können unverbindlich angefragt werden." },
      { question: "Unterstützt MTM bei Firmenumzügen?", answer: "Ja. Gewerbliche Aufträge wie Büro- oder kleinere Betriebsumzüge können passend zum Umfang angefragt werden." },
      { question: "Sind Seniorenumzüge möglich?", answer: "Ja. Bei sensiblen Umzugssituationen kann der Ablauf besonders sorgfältig und persönlich abgestimmt werden." },
      { question: "Werden Möbel getragen und verladen?", answer: "Ja. Das Tragen, Verladen und der sichere Transport gehören je nach vereinbartem Auftrag zum Leistungsumfang." },
      { question: "Kann ein Umzug mit Montage kombiniert werden?", answer: "Ja. Abbau, Transport und anschließender Aufbau von Möbeln können gemeinsam angefragt werden." },
      { question: "Kann eine Entrümpelung mit dem Umzug verbunden werden?", answer: "Ja. Nicht mehr benötigte Möbel oder Gegenstände können im Rahmen einer abgestimmten Zusatzleistung berücksichtigt werden." },
      { question: "Wie früh sollte ich meinen Umzug anfragen?", answer: "Je früher die Anfrage eingeht, desto besser lässt sich ein Wunschtermin berücksichtigen. Kurzfristige Anfragen werden trotzdem geprüft." },
      { question: "Ist meine Anfrage bereits eine Buchung?", answer: "Nein. Die Anfrage ist unverbindlich. Termin, Preis und Auftragsannahme werden erst persönlich bestätigt." },
      { question: "Wie starte ich eine Umzugsanfrage?", answer: "Über den Anfrage-Assistenten wählen Sie Umzug aus und geben die wichtigsten Informationen zum Auftrag an." },
    ],
  },
  {
    slug: "umzugsvorbereitung-verpackung",
    title: "Umzugsvorbereitung & Verpackung",
    intro: "Hilfreiche Hinweise zur Vorbereitung, zu Kartons, Fotos und wichtigen Angaben vor einem Umzug.",
    questions: [
      { question: "Welche Angaben helfen bei der Vorbereitung?", answer: "Wichtig sind Start- und Zielort, Etagen, Aufzug, Terminwunsch, ungefähre Menge sowie besondere oder schwere Gegenstände." },
      { question: "Soll ich Fotos hochladen?", answer: "Fotos sind freiwillig, helfen aber bei der Einschätzung von Möbeln, Zugängen und Besonderheiten." },
      { question: "Müssen Kartons bereits gepackt sein?", answer: "Das hängt vom vereinbarten Umfang ab. Geben Sie in der Anfrage an, wobei Sie Unterstützung benötigen." },
      { question: "Soll ich Schränke vor dem Transport ausräumen?", answer: "In der Regel sollten Schränke vor dem Transport leer sein. Ausnahmen können im Vorfeld abgestimmt werden." },
      { question: "Was ist bei empfindlichen Möbeln wichtig?", answer: "Beschreiben oder fotografieren Sie empfindliche Stücke, damit notwendiger Schutz und Transportaufwand eingeplant werden können." },
      { question: "Wie gebe ich schwere Gegenstände an?", answer: "Nennen Sie schwere oder sperrige Gegenstände ausdrücklich in der Anfrage, beispielsweise große Schränke, Geräte oder massive Möbel." },
      { question: "Soll ich die Parksituation erwähnen?", answer: "Ja. Hinweise zu Zufahrt, Entfernung zum Eingang und Parkplatzsituation erleichtern die Planung." },
      { question: "Kann ich Besonderheiten nachreichen?", answer: "Ja. Weitere Informationen können nach der ersten Anfrage im persönlichen Kontakt ergänzt werden." },
      { question: "Kann MTM Schutzmaterial einplanen?", answer: "Der benötigte Schutz für Möbel und Gegenstände wird abhängig vom Auftrag abgestimmt." },
      { question: "Was mache ich bei einem noch unklaren Umfang?", answer: "Beschreiben Sie den Auftrag zunächst so gut wie möglich. Offene Punkte werden anschließend persönlich geklärt." },
    ],
  },
  {
    slug: "firmen-bueroumzug",
    title: "Firmen- & Büroumzüge",
    intro: "Informationen für gewerbliche Kunden, Büros und betriebliche Transportaufträge.",
    questions: [
      { question: "Arbeitet MTM auch für Unternehmen?", answer: "Ja. MTM unterstützt auch gewerbliche Kunden bei Umzügen, Transporten und Montagen." },
      { question: "Sind Büromöbeltransporte möglich?", answer: "Ja. Schreibtische, Regale, Schränke und weitere Büroeinrichtung können nach Abstimmung transportiert werden." },
      { question: "Kann die Durchführung außerhalb der Betriebszeiten angefragt werden?", answer: "Solche Terminwünsche können angegeben werden und werden je nach Verfügbarkeit geprüft." },
      { question: "Sind einzelne Standortwechsel möglich?", answer: "Ja. Auch Teilumzüge, einzelne Räume oder ausgewählte Möbelbestände können angefragt werden." },
      { question: "Kann die Möbelmontage mit angeboten werden?", answer: "Ja. Demontage und Aufbau von geeigneten Möbeln können Teil des Auftrags sein." },
      { question: "Wie beschreibe ich einen Gewerbeauftrag?", answer: "Nennen Sie Art des Betriebs, Standorte, Umfang, Zugangssituation, Terminfenster und besondere Anforderungen." },
      { question: "Kann MTM kurzfristige Gewerbetransporte übernehmen?", answer: "Kurzfristige Aufträge können als Anfrage gestellt und abhängig von der Verfügbarkeit umgesetzt werden." },
      { question: "Gibt es feste Preise für Firmenumzüge?", answer: "Nein. Preise ergeben sich aus Umfang, Aufwand, Strecke und gewünschten Zusatzleistungen." },
      { question: "Können mehrere Leistungen kombiniert werden?", answer: "Ja. Transport, Montage, Räumung und Expressfahrten können je nach Bedarf kombiniert werden." },
      { question: "Wie erfolgt die Kontaktaufnahme?", answer: "Nach Ihrer Anfrage meldet sich MTM persönlich, um Ablauf und Angebot abzustimmen." },
    ],
  },
  {
    slug: "moebeltransport-lieferung",
    title: "Möbeltransport & Lieferung",
    intro: "Antworten zum sicheren Transport einzelner Möbelstücke, kompletter Einrichtungen und Lieferungen.",
    questions: [
      { question: "Transportiert MTM einzelne Möbelstücke?", answer: "Ja. Einzelne Möbel, Haushaltsgegenstände oder größere Einzelstücke können angefragt werden." },
      { question: "Sind komplette Einrichtungen möglich?", answer: "Ja. Auch umfangreichere Möbeltransporte oder komplette Einrichtungen werden nach Prüfung angeboten." },
      { question: "Kann eine Möbelabholung organisiert werden?", answer: "Ja. Geben Sie Abholort, Zielort und den Gegenstand in der Anfrage an." },
      { question: "Werden Möbel beim Transport geschützt?", answer: "Der sichere und sorgfältige Transport gehört zum Anspruch von MTM; konkrete Schutzmaßnahmen richten sich nach dem Auftrag." },
      { question: "Sind Lieferungen für Gewerbekunden möglich?", answer: "Ja. Auch gewerbliche Möbel- und Objekttransporte können angefragt werden." },
      { question: "Kann ich den Transport mit Aufbau buchen?", answer: "Ja. Möbeltransport und Montage können gemeinsam abgestimmt werden." },
      { question: "Welche Angaben sind bei Möbeltransporten wichtig?", answer: "Maße oder Fotos, Anzahl der Möbelstücke, Abhol- und Zieladresse, Etagen und Zugänge sind besonders hilfreich." },
      { question: "Kann ein Sofa oder Schrank einzeln transportiert werden?", answer: "Ja. Einzeltransporte solcher Möbelstücke sind grundsätzlich möglich." },
      { question: "Sind Transporte am selben Tag möglich?", answer: "Das kann als kurzfristige Anfrage geprüft werden; eine Zusage hängt von Verfügbarkeit und Umfang ab." },
      { question: "Wie erhalte ich ein Angebot?", answer: "Starten Sie den Anfrage-Assistenten und geben Sie die Transportdetails an. MTM meldet sich persönlich zurück." },
    ],
  },
  {
    slug: "moebelmontage-demontage",
    title: "Möbelmontage & Demontage",
    intro: "Informationen zum Auf- und Abbau von Möbeln sowie zur Kombination mit einem Transport.",
    questions: [
      { question: "Welche Möbel montiert MTM?", answer: "MTM unterstützt beim Auf- und Abbau geeigneter Möbel, Einrichtungen und ausgewählter Schrankelemente." },
      { question: "Ist nur eine Montage ohne Transport möglich?", answer: "Ja. Eine reine Montage- oder Demontageanfrage ist möglich." },
      { question: "Kann die Demontage vor einem Umzug übernommen werden?", answer: "Ja. Abbau, Transport und Wiederaufbau können gemeinsam angefragt werden." },
      { question: "Werden auch Schränke aufgebaut?", answer: "Ja. Schrankmontagen können nach Angaben oder Bildern zum Möbelstück geprüft werden." },
      { question: "Sind Küchenarbeiten möglich?", answer: "Ausgewählte Küchen- oder Schrankelemente können nach genauer persönlicher Prüfung angefragt werden." },
      { question: "Soll ich eine Aufbauanleitung bereithalten?", answer: "Falls vorhanden, kann eine Anleitung hilfreich sein. Geben Sie Besonderheiten am besten schon in der Anfrage an." },
      { question: "Kann ich Fotos des Möbels hochladen?", answer: "Ja. Fotos helfen dabei, den Umfang einer Montage besser einzuordnen." },
      { question: "Wird die Montage sauber ausgeführt?", answer: "MTM legt Wert auf eine ordentliche und sorgfältige Durchführung vor Ort." },
      { question: "Kann ich mehrere Möbelstücke montieren lassen?", answer: "Ja. Geben Sie Anzahl und Art der Möbelstücke in der Anfrage an." },
      { question: "Wie starte ich eine Montageanfrage?", answer: "Wählen Sie im Anfrage-Assistenten Möbelmontage und beschreiben Sie den gewünschten Aufbau oder Abbau." },
    ],
  },
  {
    slug: "entruempelung-entsorgung",
    title: "Entrümpelung & Entsorgung",
    intro: "Antworten zu Räumungen, Entsorgung, besenreiner Übergabe und hilfreichen Angaben für die Prüfung.",
    questions: [
      { question: "Welche Räume können entrümpelt werden?", answer: "Angefragt werden können beispielsweise Wohnungen, Keller, Garagen, Häuser oder geeignete Gewerberäume." },
      { question: "Übernimmt MTM auch die Entsorgung?", answer: "Ja. Die Entsorgung kann Bestandteil einer abgestimmten Entrümpelung sein." },
      { question: "Ist eine Haushaltsauflösung möglich?", answer: "Eine umfangreichere Räumung kann beschrieben und nach persönlicher Prüfung abgestimmt werden." },
      { question: "Kann ein Keller geräumt werden?", answer: "Ja. Keller- und Nebenraumräumungen gehören zu den typischen Anfragen." },
      { question: "Ist eine besenreine Übergabe möglich?", answer: "Eine saubere Übergabe kann bei passender Vereinbarung des Leistungsumfangs vorgesehen werden." },
      { question: "Muss vorher sortiert werden?", answer: "Nicht zwingend. Beschreiben Sie, was geräumt werden soll; der weitere Ablauf wird abgestimmt." },
      { question: "Soll ich Fotos der Räume senden?", answer: "Ja. Fotos sind besonders bei Räumungsaufträgen hilfreich, um Menge und Zugänglichkeit einzuschätzen." },
      { question: "Sind diskrete Räumungen möglich?", answer: "MTM behandelt Räumungsanfragen sorgfältig und diskret." },
      { question: "Wie wird der Preis bestimmt?", answer: "Der Preis richtet sich nach Menge, Aufwand, Zugang, Transport- und Entsorgungsbedarf." },
      { question: "Wie frage ich eine Entrümpelung an?", answer: "Wählen Sie im Anfrage-Assistenten Entrümpelung & Entsorgung und beschreiben Sie die Räume sowie den Umfang." },
    ],
  },
  {
    slug: "entkernung-rueckbau",
    title: "Entkernung & Rückbau",
    intro: "Informationen zu ausgewählten Entkernungsarbeiten, Rückbau und der notwendigen persönlichen Prüfung.",
    questions: [
      { question: "Welche Entkernungsarbeiten können angefragt werden?", answer: "Ausgewählte Rückbauarbeiten, etwa an Böden, Einbauten oder nicht tragenden Innenbereichen, können geprüft werden." },
      { question: "Ist vorab eine Prüfung notwendig?", answer: "Ja. Entkernungsarbeiten werden vor einer Zusage persönlich hinsichtlich Umfang und Machbarkeit geprüft." },
      { question: "Werden tragende Bauteile entfernt?", answer: "Solche Arbeiten werden nicht pauschal zugesagt und erfordern gegebenenfalls fachliche beziehungsweise rechtliche Prüfungen." },
      { question: "Kann Entkernung mit Entsorgung verbunden werden?", answer: "Ja, anfallendes Material und die Entsorgung können im abgestimmten Auftrag berücksichtigt werden." },
      { question: "Sind Boden- oder Einbauentfernungen möglich?", answer: "Solche Arbeiten können je nach Objekt und Umfang geprüft werden." },
      { question: "Brauche ich eine Besichtigung?", answer: "Bei Entkernungsarbeiten ist eine Besichtigung oder genaue Prüfung meist sinnvoll." },
      { question: "Welche Bilder sind hilfreich?", answer: "Fotos der Räume, Einbauten und betroffenen Flächen helfen bei der ersten Einschätzung." },
      { question: "Kann ich Entkernung direkt online buchen?", answer: "Nein. Online stellen Sie zunächst eine unverbindliche Anfrage; die Durchführung wird danach abgestimmt." },
      { question: "Arbeitet MTM auch in leerstehenden Objekten?", answer: "Geeignete Wohnungen, Häuser oder Objekte können nach persönlicher Prüfung berücksichtigt werden." },
      { question: "Wie starte ich eine Entkernungsanfrage?", answer: "Wählen Sie Sonstige Anfrage oder nennen Sie Entkernung im Anfrage-Assistenten und beschreiben Sie den Rückbauumfang." },
    ],
  },
  {
    slug: "expresstransporte",
    title: "Expresstransporte",
    intro: "Fragen zu eiligen Transporten mit 3,5-Tonnen-LKW inklusive Fahrer und kurzfristiger Verfügbarkeit.",
    questions: [
      { question: "Was ist ein Expresstransport bei MTM?", answer: "Ein kurzfristiger Transportauftrag mit 3,5-Tonnen-LKW inklusive Fahrer für eilige Fahrten oder Lieferungen." },
      { question: "Sind kurzfristige Fahrten möglich?", answer: "Ja. Kurzfristige Anfragen werden schnellstmöglich auf Verfügbarkeit geprüft." },
      { question: "Ist ein Fahrer enthalten?", answer: "Ja. Die Leistung wird als 3,5-Tonnen-LKW inklusive Fahrer angeboten." },
      { question: "Welche Güter können transportiert werden?", answer: "Geeignete Möbel, Gegenstände oder Lieferungen können nach Beschreibung und Prüfung transportiert werden." },
      { question: "Kann ich eine Abholung und Lieferung anfragen?", answer: "Ja. Geben Sie beide Orte, Zeitbedarf und Transportgut in der Anfrage an." },
      { question: "Kann eine Tragehilfe ergänzt werden?", answer: "Zusätzlicher Personal- oder Tragebedarf kann in der Anfrage angegeben und geprüft werden." },
      { question: "Ist Express nur für Gewerbe?", answer: "Nein. Auch Privatkunden können zeitkritische Transporte anfragen." },
      { question: "Gibt es jederzeit garantierte Verfügbarkeit?", answer: "Nein. Die Formulierung jederzeit anfragbar bedeutet, dass Anfragen jederzeit gestellt werden können; die Verfügbarkeit wird bestätigt." },
      { question: "Wie schnell bekomme ich eine Rückmeldung?", answer: "MTM prüft Expressanfragen so schnell wie möglich persönlich." },
      { question: "Wie starte ich eine Expressanfrage?", answer: "Wählen Sie im Anfrage-Assistenten Expresstransporte und nennen Sie Zeitraum, Strecke und Transportgut." },
    ],
  },
  {
    slug: "preise-angebote",
    title: "Preise & Angebote",
    intro: "Antworten zu unverbindlichen Anfragen, Angeboten und Faktoren, die den Preis beeinflussen.",
    questions: [
      { question: "Ist die Anfrage kostenlos und unverbindlich?", answer: "Ja. Das Absenden einer Anfrage verpflichtet Sie nicht zu einer Beauftragung." },
      { question: "Erhalte ich online sofort einen Festpreis?", answer: "Nein. Preis und Auftragsumfang werden nach Prüfung persönlich abgestimmt." },
      { question: "Wovon hängt der Preis ab?", answer: "Entscheidend sind unter anderem Umfang, Strecke, Etagen, Zugänge, Personalbedarf, Termin und Zusatzleistungen." },
      { question: "Warum werden Fotos empfohlen?", answer: "Fotos können die erste Einschätzung erleichtern und Rückfragen zum Umfang reduzieren." },
      { question: "Kann ich mehrere Leistungen gemeinsam anfragen?", answer: "Ja. Kombinierte Leistungen wie Transport plus Montage können gemeinsam berücksichtigt werden." },
      { question: "Kann sich ein Angebot nachträglich ändern?", answer: "Wenn sich der Umfang oder wichtige Bedingungen ändern, kann eine erneute Abstimmung erforderlich sein." },
      { question: "Wie erhalte ich ein Angebot?", answer: "Nach Ihrer Anfrage prüft MTM die Angaben und meldet sich zur weiteren Abstimmung." },
      { question: "Ist ein Termin ohne Bestätigung verbindlich?", answer: "Nein. Ein Termin gilt erst nach persönlicher Bestätigung als abgestimmt." },
      { question: "Kann ich ein Angebot telefonisch anfragen?", answer: "Ja. Sie können MTM direkt anrufen oder den Anfrage-Assistenten nutzen." },
      { question: "Werden Preise transparent besprochen?", answer: "Der konkrete Umfang und die daraus entstehenden Konditionen werden persönlich abgestimmt." },
    ],
  },
  {
    slug: "termin-ablauf-besichtigung",
    title: "Termin, Ablauf & Besichtigung",
    intro: "So läuft die Anfrage ab: von der ersten Nachricht über mögliche Besichtigung bis zur Durchführung.",
    questions: [
      { question: "Wie läuft eine Anfrage ab?", answer: "Sie senden die wichtigsten Informationen, MTM prüft den Auftrag und meldet sich persönlich zur Abstimmung." },
      { question: "Kann ich einen Wunschtermin angeben?", answer: "Ja. Wunschdatum oder alternativer Zeitraum können im Anfrage-Assistenten angegeben werden." },
      { question: "Sind kurzfristige Termine möglich?", answer: "Kurzfristige Termine können angefragt und abhängig von der Verfügbarkeit bestätigt werden." },
      { question: "Wann ist eine Besichtigung sinnvoll?", answer: "Bei umfangreichen Räumungen, Entkernung oder unklaren Bedingungen kann eine Besichtigung sinnvoll sein." },
      { question: "Muss immer eine Besichtigung stattfinden?", answer: "Nein. Bei klar beschriebenen kleineren Aufträgen kann eine Abstimmung anhand der Angaben ausreichen." },
      { question: "Wie erfährt MTM von Besonderheiten?", answer: "Nutzen Sie die Freitextfelder und optional Bilder im Anfrage-Assistenten." },
      { question: "Wird der Ablauf vorab erklärt?", answer: "Ja. Offene Punkte werden vor einer Durchführung persönlich abgestimmt." },
      { question: "Kann ein Termin verschoben werden?", answer: "Änderungen sollten so früh wie möglich persönlich abgestimmt werden." },
      { question: "Wie lange dauert ein Auftrag?", answer: "Die Dauer hängt vom Umfang, den Wegen, Zugängen und Zusatzleistungen ab und wird passend eingeschätzt." },
      { question: "Wann gilt der Auftrag als bestätigt?", answer: "Erst nach persönlicher Abstimmung von Umfang, Termin und Annahme durch MTM." },
    ],
  },
  {
    slug: "einsatzgebiet-zugang",
    title: "Einsatzgebiet, Zufahrt & Etagen",
    intro: "Informationen zur Region Hannover, zur Zugänglichkeit am Einsatzort und zu wichtigen örtlichen Angaben.",
    questions: [
      { question: "Wo ist MTM im Einsatz?", answer: "MTM ist in Hannover & Umland sowie in der Region Hannover für passende Aufträge erreichbar." },
      { question: "Sind Einsätze außerhalb Hannovers möglich?", answer: "Ja. Umliegende Orte der Region können je nach Auftrag und Verfügbarkeit angefragt werden." },
      { question: "Warum sind Etagen wichtig?", answer: "Etagen und Treppen beeinflussen den Aufwand und sollten bei der Anfrage angegeben werden." },
      { question: "Soll ich einen Aufzug nennen?", answer: "Ja. Ein vorhandener oder fehlender Aufzug ist eine wichtige Angabe für die Planung." },
      { question: "Ist die Parksituation relevant?", answer: "Ja. Entfernung zwischen Fahrzeug und Eingang sowie Zufahrtsmöglichkeiten beeinflussen den Ablauf." },
      { question: "Was bei engen Treppenhäusern?", answer: "Beschreiben Sie die Situation oder laden Sie Fotos hoch, besonders bei sperrigen Möbeln." },
      { question: "Kann ich mehrere Einsatzorte nennen?", answer: "Ja. Start- und Zieladresse sowie weitere Zwischenstopps können im Kontakt abgestimmt werden." },
      { question: "Sind Keller ohne Aufzug möglich?", answer: "Solche Aufträge können angefragt werden; der Aufwand wird anhand der Situation geprüft." },
      { question: "Muss ich meine vollständige Adresse sofort nennen?", answer: "Für eine konkrete Planung sind Einsatzorte hilfreich; für erste Fragen können Sie auch telefonisch Kontakt aufnehmen." },
      { question: "Wo sehe ich das Einsatzgebiet?", answer: "Auf der Kontaktseite finden Sie den Kartenblock zur Region Hannover und die Kontaktmöglichkeiten." },
    ],
  },
  {
    slug: "kontakt-anfrage-datenschutz",
    title: "Kontakt, Anfrage-Assistent & Datenschutz",
    intro: "Antworten zu Kontaktmöglichkeiten, Foto-Uploads, Datenverarbeitung und dem unverbindlichen Anfrage-Assistenten.",
    questions: [
      { question: "Wie erreiche ich MTM?", answer: "Sie erreichen MTM über die angegebene Telefonnummer, per E-Mail oder über den Anfrage-Assistenten." },
      { question: "Was macht der Anfrage-Assistent?", answer: "Er führt Schritt für Schritt durch die Angaben, die MTM zur Prüfung Ihres Auftrags benötigt." },
      { question: "Welche Kontaktdaten werden benötigt?", answer: "Für eine Rückmeldung werden Name, Telefonnummer und E-Mail-Adresse abgefragt." },
      { question: "Kann ich einen Rückruf wünschen?", answer: "Ja. Im Anfrage-Assistenten kann ein Rückrufwunsch ausgewählt werden." },
      { question: "Kann ich Fotos hochladen?", answer: "Ja. Optional können bis zu drei Bilder im Format JPG, PNG oder WEBP hochgeladen werden." },
      { question: "Wie groß dürfen Bilder sein?", answer: "Die technische Begrenzung liegt bei maximal 4 MB je Bild und insgesamt maximal 10 MB." },
      { question: "Ist das Absenden verbindlich?", answer: "Nein. Die Anfrage ist unverbindlich und führt nicht automatisch zu einem Vertrag." },
      { question: "Wie werden meine Angaben verwendet?", answer: "Die Angaben werden zur Prüfung Ihrer Anfrage und zur anschließenden Kontaktaufnahme verarbeitet." },
      { question: "Wo finde ich weitere Datenschutzinformationen?", answer: "Die ausführlichen Informationen stehen auf der Seite Datenschutz im Footer der Webseite." },
      { question: "Was passiert, wenn der Online-Versand nicht eingerichtet ist?", answer: "Dann zeigt die Webseite einen Hinweis an und verweist auf die direkte Kontaktaufnahme per Telefon oder E-Mail." },
    ],
  },
];

export function getFaqSection(slug: string): FaqSection | undefined {
  return faqSections.find((section) => section.slug === slug);
}
