export type ContentBlock =
  | { type: "paragraph"; text: string }
  | { type: "heading2"; text: string }
  | { type: "heading3"; text: string }
  | { type: "list"; items: string[] }
  | { type: "note"; text: string };

export type RatgeberArticle = {
  slug: string;
  title: string;
  description: string;
  category: string;
  content: ContentBlock[];
};

export const ratgeberArticles: RatgeberArticle[] = [
  {
    slug: "was-kostet-umzug-hannover",
    title: "Was kostet ein Umzug in Hannover?",
    description: "Preise, Faktoren und worauf Sie bei der Kostenplanung achten sollten.",
    category: "Umzug",
    content: [
      { type: "paragraph", text: "Wer in Hannover umziehen möchte, stellt sich früh die Frage: Was kostet mich das eigentlich? Die Antwort hängt von mehreren Faktoren ab – aber mit den richtigen Informationen können Sie realistisch planen und böse Überraschungen vermeiden." },
      { type: "heading2", text: "Grobe Richtwerte für einen Umzug in Hannover" },
      { type: "paragraph", text: "Die tatsächlichen Kosten eines Umzugs hängen von vielen individuellen Faktoren ab und können stark variieren. Folgende Richtwerte dienen nur zur groben Orientierung – das endgültige Angebot ergibt sich immer erst nach einer konkreten Anfrage." },
      { type: "list", items: ["1-Zimmer-Wohnung: ab ca. 600 €", "2-Zimmer-Wohnung: ab ca. 900 €", "3-Zimmer-Wohnung: ab ca. 1.400 €", "4-Zimmer-Wohnung oder Haus: ab ca. 2.000 €"] },
      { type: "note", text: "Diese Richtwerte gelten für einen einfachen Umzug mit zwei bis drei Helfern und einem Transportfahrzeug. Je nach Aufwand, Stockwerk, Entfernung und Zusatzleistungen kann der Preis erheblich abweichen." },
      { type: "heading2", text: "Welche Faktoren beeinflussen den Preis?" },
      { type: "heading3", text: "Entfernung" },
      { type: "paragraph", text: "Bei einem Umzug innerhalb Hannovers fallen geringere Fahrtkosten an als bei einem Umzug in eine andere Stadt. Kurze Wege bedeuten weniger Stunden und damit geringere Kosten." },
      { type: "heading3", text: "Stockwerk und Aufzug" },
      { type: "paragraph", text: "Ein Umzug aus dem Erdgeschoss ist deutlich günstiger als aus dem 4. Obergeschoss ohne Aufzug. Jede Etage bedeutet mehr Zeit und mehr körperlichen Aufwand für das Team." },
      { type: "heading3", text: "Menge und Gewicht der Möbel" },
      { type: "paragraph", text: "Schwere Gegenstände wie Klaviere, Tresore oder große Sofas erfordern Spezialausrüstung und mehr Personal. Das schlägt sich im Preis nieder." },
      { type: "heading3", text: "Halteverbotszonen" },
      { type: "paragraph", text: "In Hannover sind für größere Umzüge oft Halteverbotszonen notwendig. Diese müssen beim Ordnungsamt beantragt werden und verursachen zusätzliche Kosten." },
      { type: "heading3", text: "Saison und Termin" },
      { type: "paragraph", text: "Umzüge am Monatsende oder im Sommer sind stark nachgefragt. Wer flexibel ist und unter der Woche oder in der Nebensaison umzieht, kann oft günstiger buchen." },
      { type: "heading2", text: "Was ist im Preis enthalten?" },
      { type: "paragraph", text: "Bei MTM Service umfasst ein Standardumzug in der Regel An- und Abfahrt mit einem geeigneten Transportfahrzeug, Be- und Entladen aller Möbel sowie Schutzdecken für empfindliche Möbelstücke. Optional hinzubuchbar sind Auf- und Abbau von Möbeln, Verpackungsservice sowie die Entsorgung von Altmöbeln." },
      { type: "heading2", text: "Fazit" },
      { type: "paragraph", text: "Die Kosten eines Umzugs in Hannover lassen sich gut planen, wenn Sie die wichtigsten Faktoren im Blick behalten. Am besten holen Sie sich ein konkretes Angebot – so gibt es keine unerwarteten Kosten am Umzugstag." },
    ],
  },
  {
    slug: "moebelmontage-hannover",
    title: "Möbelmontage Hannover: IKEA und andere Möbel aufbauen lassen",
    description: "Warum sich professionelle Möbelmontage lohnt – für IKEA, Küchen und alle anderen Hersteller.",
    category: "Möbelmontage",
    content: [
      { type: "paragraph", text: "Neue Möbel kaufen macht Freude – der Aufbau meist weniger. Wer in Hannover Möbel aufbauen lassen möchte, findet mit MTM Service einen zuverlässigen Partner für IKEA-Montagen und alle anderen Hersteller." },
      { type: "heading2", text: "Warum Möbelmontage vom Profi?" },
      { type: "paragraph", text: "Professionelle Monteure haben die Werkzeuge, das Wissen und die Routine – und bauen in der Zeit, die man selbst für ein einzelnes Regal braucht, ein ganzes Schlafzimmer auf. Falsch montierte Möbel können wackeln, sich verziehen oder im schlimmsten Fall umfallen. Ein Profi baut sicher und fachgerecht." },
      { type: "heading2", text: "Was wird montiert?" },
      { type: "list", items: ["IKEA-Möbel – PAX, KALLAX, BILLY, BESTA, MALM und alle weiteren Serien", "Küchenmontage – Ober- und Unterschränke, Arbeitsplatten", "Schlafzimmermöbel – Betten, Kleiderschränke, Kommoden", "Wohnzimmermöbel – Regale, Sideboards, TV-Möbel", "Büromöbel – Schreibtische, Aktenschränke", "Badmöbel – Spiegelschränke, Unterschränke", "Garderoben und Einbaulösungen"] },
      { type: "heading2", text: "IKEA-Montage in Hannover: besonders gefragt" },
      { type: "paragraph", text: "IKEA-Möbel sind in Hannover sehr beliebt. MTM-Monteure kennen alle gängigen IKEA-Systeme und bauen schnell und sauber auf. Das Verpackungsmaterial wird nach der Montage auf Wunsch mitgenommen und entsorgt." },
      { type: "heading2", text: "Wie läuft eine Möbelmontage ab?" },
      { type: "list", items: ["Anfrage stellen – kurze Beschreibung welche Möbel aufgebaut werden sollen", "Termin vereinbaren – flexibel auch kurzfristig möglich", "Aufbau vor Ort – Monteure kommen mit allem nötigen Werkzeug", "Fertig – Möbel stehen, Kartons werden auf Wunsch entsorgt"] },
      { type: "heading2", text: "Was kostet Möbelmontage in Hannover?" },
      { type: "paragraph", text: "Die Kosten hängen von der Anzahl und Komplexität der Möbel ab und können variieren. Für eine genaue Einschätzung ist eine Anfrage mit der Liste der aufzubauenden Möbel am besten – MTM gibt schnell eine transparente Preisauskunft." },
      { type: "heading2", text: "Kombination mit Umzug oder Transport" },
      { type: "paragraph", text: "Besonders praktisch: Möbelmontage und Möbeltransport aus einer Hand. MTM transportiert Ihre Möbel und baut sie direkt am neuen Standort wieder auf – kein separates Koordinieren verschiedener Dienstleister." },
    ],
  },
  {
    slug: "entruempelung-hannover",
    title: "Entrümpelung Hannover: Ablauf, Kosten und worauf Sie achten sollten",
    description: "Alles Wichtige zur professionellen Entrümpelung in Hannover – von der Anfrage bis zur besenreinen Übergabe.",
    category: "Entrümpelung",
    content: [
      { type: "paragraph", text: "Eine Entrümpelung ist keine alltägliche Aufgabe – ob nach einem Todesfall, einem Umzug ins Pflegeheim oder weil sich über Jahre zu viel angesammelt hat. MTM Service übernimmt Entrümpelungen in Hannover und Umgebung professionell, schnell und diskret." },
      { type: "heading2", text: "Wann wird eine Entrümpelung beauftragt?" },
      { type: "list", items: ["Wohnungsauflösung nach Auszug oder Kündigung", "Nachlass nach dem Tod eines Angehörigen", "Umzug ins Pflegeheim – der bisherige Haushalt muss aufgelöst werden", "Keller oder Dachboden jahrelang nicht ausgemistet", "Erbschaft einer fremden Immobilie", "Gewerbliche Entrümpelung von Büros oder Lagerräumen"] },
      { type: "heading2", text: "Wie läuft eine Entrümpelung mit MTM ab?" },
      { type: "heading3", text: "1. Besichtigung und Angebot" },
      { type: "paragraph", text: "Zuerst wird das Objekt begutachtet – vor Ort oder per Fotos. Danach gibt es ein konkretes Festpreisangebot ohne versteckte Kosten." },
      { type: "heading3", text: "2. Terminvereinbarung" },
      { type: "paragraph", text: "Entrümpelungen werden flexibel terminiert, auch kurzfristig. In vielen Fällen ist ein Einsatz innerhalb weniger Tage möglich." },
      { type: "heading3", text: "3. Entrümpelung vor Ort" },
      { type: "paragraph", text: "Das MTM-Team räumt alle zu entsorgenden Gegenstände aus, trennt verwertbare von nicht verwertbaren Materialien und transportiert alles ab." },
      { type: "heading3", text: "4. Übergabe" },
      { type: "paragraph", text: "Nach der Entrümpelung wird das Objekt besenrein übergeben – bereit für die nächste Nutzung oder Übergabe an den Vermieter." },
      { type: "heading2", text: "Was kostet eine Entrümpelung in Hannover?" },
      { type: "paragraph", text: "Die Kosten hängen von Größe, Füllstand und Art der zu entsorgenden Gegenstände ab und können stark variieren. Folgende Richtwerte dienen nur zur groben Orientierung:" },
      { type: "list", items: ["Keller oder einzelner Raum: ab ca. 300 €", "1–2 Zimmer Wohnung: ab ca. 500 €", "3–4 Zimmer Wohnung: ab ca. 900 €", "Haus oder größeres Objekt: individuell nach Aufwand"] },
      { type: "note", text: "Der tatsächliche Preis ergibt sich immer erst nach Besichtigung oder detaillierter Beschreibung des Objekts." },
      { type: "heading2", text: "Sondersituation: Entrümpelung nach Todesfall" },
      { type: "paragraph", text: "Eine Wohnungsauflösung nach dem Tod eines Angehörigen ist emotional belastend. MTM geht in solchen Situationen besonders sensibel vor – diskret, rücksichtsvoll und ohne unnötigen Zeitdruck." },
    ],
  },
  {
    slug: "umzug-checkliste-hannover",
    title: "Umzug Checkliste Hannover: So planen Sie stressfrei",
    description: "Die komplette Schritt-für-Schritt-Checkliste für Ihren Umzug in Hannover – von 8 Wochen vorher bis nach dem Einzug.",
    category: "Umzug",
    content: [
      { type: "paragraph", text: "Ein Umzug ist einer der aufwendigsten Vorgänge im Alltag. Wer rechtzeitig plant und die richtigen Schritte in der richtigen Reihenfolge angeht, spart sich Stress, Zeit und Geld." },
      { type: "heading2", text: "8 Wochen vor dem Umzug" },
      { type: "list", items: ["Umzugsdatum festlegen – Monatsende und Sommer sind teurer und stark gebucht", "Umzugsunternehmen anfragen und Termin sichern", "Kündigung der alten Wohnung prüfen – Kündigungsfristen beachten (oft 3 Monate)", "Neue Wohnung besichtigen und Maße nehmen", "Nachsendeauftrag bei der Post beantragen"] },
      { type: "heading2", text: "6 Wochen vor dem Umzug" },
      { type: "list", items: ["Ummeldung vorbereiten – in Hannover beim Bürgeramt, innerhalb von 2 Wochen nach Einzug", "Verträge ummelden: Strom, Gas, Internet, Versicherungen", "Kita, Schule, Arbeitgeber über neue Adresse informieren", "Halteverbotszone beantragen – beim Stadtbezirk, mind. 4 Wochen vorher"] },
      { type: "heading2", text: "4 Wochen vor dem Umzug" },
      { type: "list", items: ["Umzugskartons beschaffen", "Packpapier, Luftpolsterfolie, Klebeband besorgen", "Nicht benötigte Sachen aussortieren – verkaufen, verschenken oder entsorgen", "Mit dem Packen anfangen – selten genutzte Dinge zuerst"] },
      { type: "heading2", text: "1 Woche vor dem Umzug" },
      { type: "list", items: ["Fast alles einpacken – nur das Nötigste für die letzte Woche auspacken lassen", "Kartons beschriften – Raum + kurzer Inhalt (z.B. \"Küche – Töpfe\")", "Zählerstände in der alten Wohnung notieren und fotografieren", "Reinigungsmittel und Werkzeug separat einpacken und zugänglich halten"] },
      { type: "heading2", text: "Am Umzugstag" },
      { type: "list", items: ["Früh aufstehen – Umzüge dauern oft länger als geplant", "Wertvolle Gegenstände selbst transportieren", "Zählerstände in der neuen Wohnung fotografieren", "Schlüsselübergabe der alten Wohnung organisieren"] },
      { type: "heading2", text: "Nach dem Umzug" },
      { type: "list", items: ["Ummeldung innerhalb von 2 Wochen beim Bürgeramt Hannover", "KFZ ummelden bei der KFZ-Zulassungsstelle Hannover", "Neue Adresse mitteilen an: Bank, Finanzamt, Krankenversicherung, Arbeitgeber", "Zählerstände beim neuen Energieversorger melden"] },
    ],
  },
  {
    slug: "moebeltransport-hannover",
    title: "Möbeltransport Hannover: Einzelne Möbelstücke sicher transportieren",
    description: "Wann ein einzelner Möbeltransport sinnvoll ist und wie er mit MTM in Hannover reibungslos abläuft.",
    category: "Transport",
    content: [
      { type: "paragraph", text: "Nicht jeder braucht einen kompletten Umzug. Manchmal muss nur ein einzelnes Sofa, ein schwerer Schrank oder eine neue Küche transportiert werden. MTM Service bietet Möbeltransporte in Hannover und Umgebung – flexibel, schnell und zu fairen Preisen." },
      { type: "heading2", text: "Wann macht ein einzelner Möbeltransport Sinn?" },
      { type: "list", items: ["Neukauf: Möbel wurden bestellt, aber der Lieferservice ist teuer oder nicht verfügbar", "Kauf eines gebrauchten Möbelstücks vom Marktplatz", "Möbel sollen zwischen Wohnungen oder Etagen umgezogen werden", "Sperrige Einzelstücke wie Klavier, Tresor oder Aquarium", "Gewerbliche Möbelanlieferungen"] },
      { type: "heading2", text: "Was wird transportiert?" },
      { type: "list", items: ["Sofas und Couchgarnituren", "Kleiderschränke und Aktenschränke", "Betten und Matratzen", "Esstische und Stühle", "Küchen und Einbauküchen", "Waschmaschinen und Haushaltsgeräte", "Klaviere und andere schwere Sondergegeständen"] },
      { type: "heading2", text: "Was kostet ein Möbeltransport in Hannover?" },
      { type: "paragraph", text: "Die Kosten variieren je nach Aufwand erheblich. Als grobe Orientierung starten einzelne Transporte innerhalb Hannovers ab ca. 150 €. Der tatsächliche Preis hängt ab von Anzahl und Gewicht der Möbel, Stockwerk und Aufzugsverfügbarkeit sowie der Entfernung zwischen Abhol- und Lieferadresse." },
      { type: "note", text: "Für eine genaue Preisauskunft einfach kurz anfragen – MTM nennt schnell einen konkreten Preis." },
      { type: "heading2", text: "Transport aus dem Möbelhaus oder IKEA" },
      { type: "paragraph", text: "Sie haben neue Möbel beim IKEA Hannover gekauft und brauchen Transport und Aufbau? MTM holt Ihre Möbel direkt ab und baut sie bei Ihnen auf – alles aus einer Hand." },
    ],
  },
  {
    slug: "expresstransport-hannover",
    title: "Expresstransport Hannover: Kurzfristig und schnell transportieren",
    description: "Wann ein Expresstransport in Hannover sinnvoll ist und wie schnell MTM reagieren kann.",
    category: "Transport",
    content: [
      { type: "paragraph", text: "Manchmal muss es schnell gehen. Ein Auftrag kurzfristig, ein Liefertermin verpasst oder eine spontane Situation – MTM Service bietet Expresstransporte in Hannover und der Region, die auch auf Kurznotice möglich sind." },
      { type: "heading2", text: "Typische Einsätze für Expresstransporte" },
      { type: "list", items: ["Kurzfristige Lieferungen – Ware oder Möbel müssen noch heute ankommen", "Notfallsituationen – Wasserschaden, plötzlicher Auszug, dringende Räumung", "Geschäftliche Eillieferungen – Büromaterial, Ausstellungsstücke, Messe-Equipment", "Einkäufe ohne eigenen Transport – großes Gerät aus dem Markt", "Abholung und Lieferung am gleichen Tag"] },
      { type: "heading2", text: "Wie kurzfristig ist kurzfristig?" },
      { type: "paragraph", text: "MTM Service kann in vielen Fällen noch am selben Tag oder am nächsten Tag verfügbar sein – je nach aktueller Auslastung. Eine kurze Anfrage klärt die Verfügbarkeit schnell." },
      { type: "heading2", text: "Expresstransport vs. Paketdienst" },
      { type: "paragraph", text: "Paketdienste wie DHL oder DPD sind für kleine Pakete geeignet. Für sperrige, schwere oder empfindliche Güter – und wenn Auf- oder Abladen Hilfe erfordert – ist ein professioneller Transportdienst die bessere Wahl. MTM kommt mit eigenem Fahrzeug und Personal direkt zu Ihnen." },
      { type: "heading2", text: "Region: Hannover und Umgebung" },
      { type: "paragraph", text: "MTM ist in Hannover und im Umland aktiv – von Garbsen und Langenhagen über Lehrte bis Springe. Auch überregionale Transporte sind nach Absprache möglich." },
    ],
  },
  {
    slug: "buerouzmug-hannover",
    title: "Büroumzug Hannover: Gewerblicher Umzug ohne Betriebsunterbrechung",
    description: "Wie ein Büroumzug in Hannover professionell und mit minimalem Betriebsausfall abläuft.",
    category: "Gewerbe",
    content: [
      { type: "paragraph", text: "Ein Büroumzug ist kein privater Umzug – er muss geplant, schnell und professionell ablaufen, damit der Geschäftsbetrieb so wenig wie möglich gestört wird. MTM Service führt Büro- und Gewerbeumzüge in Hannover durch und weiß, worauf es dabei ankommt." },
      { type: "heading2", text: "Was macht einen Büroumzug anders?" },
      { type: "paragraph", text: "Bei einem privaten Umzug kann man sich ein paar Tage Zeit lassen. Bei einem Unternehmensumzug zählt jede Stunde. Mitarbeiter brauchen ihren Arbeitsplatz, Kunden erwarten Erreichbarkeit, und IT-Systeme dürfen nicht länger als nötig offline sein." },
      { type: "heading2", text: "Was übernimmt MTM beim Büroumzug?" },
      { type: "list", items: ["Demontage und Abbau von Schreibtischen, Regalen und Einrichtung", "Fachgerechter Transport aller Büromöbel und Geräte", "Wiederaufbau am neuen Standort nach Ihrem Raumplan", "Entsorgung von nicht mehr benötigtem Inventar", "Schnelle Durchführung – auch am Wochenende oder über Nacht"] },
      { type: "heading2", text: "Planung ist alles" },
      { type: "paragraph", text: "Ein erfolgreicher Büroumzug in Hannover beginnt mit einem klaren Plan: Bestandsaufnahme was mitzieht, Raumplan für den neuen Standort, IT-Koordination und klare Kommunikation mit den Mitarbeitern. MTM berät Sie gerne bei der Planung." },
      { type: "heading2", text: "Umzug außerhalb der Geschäftszeiten" },
      { type: "paragraph", text: "Viele Unternehmen entscheiden sich für einen Büroumzug am Wochenende oder in den Abendstunden, um den laufenden Betrieb nicht zu unterbrechen. MTM ist flexibel und führt Umzüge auch außerhalb der regulären Arbeitszeiten durch." },
      { type: "heading2", text: "Welche Unternehmenstypen profitieren?" },
      { type: "list", items: ["Arztpraxen und Kanzleien – empfindliche Unterlagen, hohe Diskretion nötig", "Handelsunternehmen – Lager und Büro koordiniert umziehen", "Start-ups und Agenturen – schnelles Wachstum erfordert flexibles Umziehen", "Einrichtungen und Behörden", "Einzelhandel – Ladenumzug mit Inventar und Einrichtung"] },
    ],
  },
  {
    slug: "wohnungsaufloesung-hannover",
    title: "Wohnungsauflösung Hannover: Kosten, Ablauf und was zu beachten ist",
    description: "Alles zur professionellen Wohnungsauflösung in Hannover – transparent, schnell und besenrein.",
    category: "Entrümpelung",
    content: [
      { type: "paragraph", text: "Eine Wohnungsauflösung entsteht in Lebenssituationen, die oft herausfordernd sind – und erfordert schnelles, strukturiertes Handeln. MTM Service übernimmt Wohnungsauflösungen in Hannover professionell und zum Festpreis." },
      { type: "heading2", text: "Typische Anlässe" },
      { type: "list", items: ["Tod eines Angehörigen – die Wohnung muss aufgelöst werden", "Umzug ins Pflegeheim oder Betreutes Wohnen", "Scheidung oder Trennung – gemeinsamer Haushalt wird aufgelöst", "Verkauf einer Immobilie – Haus oder Wohnung muss leergeräumt werden"] },
      { type: "heading2", text: "Ablauf einer Wohnungsauflösung mit MTM" },
      { type: "list", items: ["Besichtigung und Angebot – vor Ort oder per Fotos, danach Festpreisangebot", "Terminvereinbarung – oft kurzfristig möglich", "Aussortieren – persönliche Gegenstände können vorab gesichert werden", "Räumung – vollständiges Ausräumen, Trennung und Abtransport", "Besenreine Übergabe – bereit für die Schlüsselübergabe"] },
      { type: "heading2", text: "Was kostet eine Wohnungsauflösung in Hannover?" },
      { type: "paragraph", text: "Die Kosten hängen von Größe, Füllstand und Zustand des Objekts ab und können erheblich variieren. Folgende Richtwerte sind nur als grobe Orientierung zu verstehen – der endgültige Preis ergibt sich nach Besichtigung:" },
      { type: "list", items: ["1-Zimmer-Wohnung: ab ca. 500 €", "2-Zimmer-Wohnung: ab ca. 750 €", "3-Zimmer-Wohnung: ab ca. 1.200 €", "Haus oder größere Wohnung: individuell nach Aufwand"] },
      { type: "note", text: "Werthaltige Möbel oder Gegenstände können den Preis reduzieren, da sie weiterverkauft oder gespendet werden." },
      { type: "heading2", text: "Was passiert mit dem Inhalt?" },
      { type: "paragraph", text: "MTM sortiert gewissenhaft: Gut erhaltene Möbel gehen an Second-Hand-Läden oder Sozialkaufhäuser. Brauchbare Elektrogeräte werden weitergegeben oder recycelt. Restmüll und Sondermüll werden fachgerecht entsorgt." },
    ],
  },
  {
    slug: "umzug-tipps-hannover",
    title: "10 Tipps für einen reibungslosen Umzug in Hannover",
    description: "Die häufigsten Fehler beim Umzug – und wie Sie sie vermeiden.",
    category: "Umzug",
    content: [
      { type: "paragraph", text: "Ob erster eigener Umzug oder der zehnte Wohnungswechsel – bestimmte Fehler machen fast alle. Diese Tipps helfen Ihnen, Ihren Umzug in Hannover entspannter und effizienter zu gestalten." },
      { type: "heading2", text: "1. Früh genug buchen" },
      { type: "paragraph", text: "Gute Umzugsunternehmen in Hannover sind vor allem im Sommer und zu Monatsenden schnell ausgebucht. Planen Sie mindestens 4–6 Wochen im Voraus." },
      { type: "heading2", text: "2. Halteverbotszone rechtzeitig beantragen" },
      { type: "paragraph", text: "In Hannover müssen Halteverbotszonen beim zuständigen Stadtbezirk beantragt werden. Das dauert in der Regel 2–3 Wochen – ohne reservierten Parkplatz kann ein Umzugstag deutlich länger werden." },
      { type: "heading2", text: "3. Ausmisten vor dem Umzug" },
      { type: "paragraph", text: "Was Sie mitnehmen, muss auch irgendwann wieder ausgepackt werden. Gehen Sie vor dem Packen konsequent durch jeden Raum. Das spart Kartons, Transportgewicht und Arbeit." },
      { type: "heading2", text: "4. Kartons richtig packen" },
      { type: "list", items: ["Schwere Dinge (Bücher, Werkzeug) in kleine Kartons", "Leichte Dinge (Bettwäsche, Kleidung) in große Kartons", "Kartons nie zu voll machen – sie müssen stapelbar und tragbar bleiben", "Jeden Karton oben und an den Seiten beschriften"] },
      { type: "heading2", text: "5. Eine Erste-Nacht-Box packen" },
      { type: "paragraph", text: "Packen Sie eine separate Kiste mit allem, was Sie am ersten Abend und Morgen brauchen: Toilettenartikel, Schlafzeug, Ladekabel, Kaffeekocher, Tassen, wichtige Dokumente." },
      { type: "heading2", text: "6. Zählerstände fotografieren" },
      { type: "paragraph", text: "Fotografieren Sie vor dem Auszug alle Zählerstände – Strom, Gas, Wasser. Machen Sie das gleiche beim Einzug in die neue Wohnung. Das schützt vor Streitigkeiten." },
      { type: "heading2", text: "7. Die neue Wohnung vorher ausmessen" },
      { type: "paragraph", text: "Passen alle Möbel durch die Türen? Ist der Kleiderschrank so groß wie der neue Raum erlaubt? Messen Sie vorher nach." },
      { type: "heading2", text: "8. Adressänderungen nicht vergessen" },
      { type: "paragraph", text: "In Deutschland müssen Sie sich innerhalb von zwei Wochen nach dem Umzug ummelden. Dazu kommen Bank, Finanzamt, Krankenversicherung, Arbeitgeber und alle Abos. Ein Nachsendeauftrag bei der Post (3–12 Monate) sorgt dafür, dass keine Briefe verloren gehen." },
      { type: "heading2", text: "9. Schäden dokumentieren" },
      { type: "paragraph", text: "Gehen Sie bei Ein- und Auszug systematisch durch alle Räume und fotografieren Sie vorhandene Schäden. Das schützt Sie vor ungerechtfertigten Abzügen von der Kaution." },
      { type: "heading2", text: "10. Trinkgeld einplanen" },
      { type: "paragraph", text: "Ein Trinkgeld von 5–10 € pro Person für das Umzugsteam ist eine nette Geste und wird immer geschätzt." },
    ],
  },
  {
    slug: "entkernung-hannover",
    title: "Entkernung Hannover: Innenräume professionell zurückbauen lassen",
    description: "Was eine Entkernung bedeutet, wann sie sinnvoll ist und wie sie mit MTM in Hannover abläuft.",
    category: "Entkernung",
    content: [
      { type: "paragraph", text: "Bevor eine Renovierung oder ein Umbau beginnen kann, muss oft erst der Ist-Zustand rückgebaut werden. Entkernung bedeutet: Wände, Böden, Decken, Installationen und Einbauten werden fachgerecht entfernt – bis auf die tragenden Strukturen. MTM Service führt Entkernungen in Hannover und Umgebung durch." },
      { type: "heading2", text: "Was ist eine Entkernung?" },
      { type: "paragraph", text: "Bei einer Entkernung wird der Innenausbau eines Gebäudes oder einzelner Räume vollständig oder teilweise zurückgebaut. Das Ziel: eine rohe Hülle, die für den neuen Ausbau bereit ist." },
      { type: "heading2", text: "Wann ist eine Entkernung notwendig?" },
      { type: "list", items: ["Sanierung eines Altbaus – alte Substanz wird entfernt, bevor neu aufgebaut wird", "Umbau von Gewerberäumen – Laden oder Büro wird komplett neu gestaltet", "Schimmelbefall – betroffene Wände müssen vollständig entfernt werden", "Wasserschaden – Böden und Wände müssen geöffnet werden", "Umnutzung einer Immobilie – z.B. aus einem alten Büro wird Wohnraum"] },
      { type: "heading2", text: "Was wird bei einer Entkernung entfernt?" },
      { type: "list", items: ["Bodenbeläge – Fliesen, Parkett, Laminat, Teppich", "Wandverkleidungen – Fliesen, Gipskarton, Holzpaneele", "Abgehängte Decken und Dämmung", "Nicht-tragende Wände", "Türen und Zargen", "Einbaumöbel – Küchen, Einbauschränke"] },
      { type: "heading2", text: "Was kostet eine Entkernung in Hannover?" },
      { type: "paragraph", text: "Die Kosten hängen stark von Fläche, Art der Materialien und Entsorgungsaufwand ab – pauschale Preise sind kaum seriös nennbar. Als grobe Orientierung: Einzelraum ab ca. 600 €, Wohnung ab ca. 2.000 €. Der tatsächliche Preis kann je nach Zustand und Umfang deutlich höher liegen." },
      { type: "note", text: "Achtung: Asbest kann in Altbauten vorkommen, die vor 1990 gebaut wurden. Vor einer Entkernung sollte eine Asbestprüfung durchgeführt werden." },
      { type: "heading2", text: "Entsorgung des Abbruchmaterials" },
      { type: "paragraph", text: "MTM trennt sorgfältig: Mineralische Abfälle wie Beton und Ziegel werden recycelt, Metalle dem Schrotthandel zugeführt, Schadstoffe durch zertifizierte Partner fachgerecht entsorgt." },
    ],
  },
];

export function getRatgeberArticle(slug: string): RatgeberArticle | undefined {
  return ratgeberArticles.find((a) => a.slug === slug);
}
